# backend-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fitai-backend-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "fitai-static-ip"
    networking.gke.io/managed-certificates: "fitai-certificate"
spec:
  rules:
  - host: 34-8-10-114.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fitai-backend
            port:
              number: 80